### ISSUE TITLE
Listing suggestions for documentation updates

### ISSUE THREAD

**Issue by yzerlaut** [HumanBrainProject/fairgraph#11]
1) Fix the [Nexus query API](https://bbp-nexus.epfl.ch/staging/docs/kg/api-reference/operating-on-resources.html#search-and-filtering) link. The current link of the documentation is broken.

2) Include a description of the "namespace" aspect (N.B. the documentation refers also to "modules", are they interchangeable?), list the different namespaces in the KG, how `fairgraph` is intended to be used with those different modules, for which type of users...

3) Describe the use of `fairgraph` for different users: data curators, model curators, model validation users, ...

4) Could we point to the ontology description of the HBP KG ?

**Comment by apdavison** [comment]
closing because outdated
