### ISSUE TITLE
Cannot download R2G dataset

### ISSUE THREAD

**Issue by dizcza** [HumanBrainProject/fairgraph#39]
I'm trying to download R2G dataset outside of the HBP Collab.
I've installed fairgraph from the master branch and acquired an access token from the HBP website.
```python
from fairgraph.client import KGClient
from fairgraph.minds import Dataset
import os
token = os.environ['HBP_AUTH_TOKEN']
client = KGClient(token)
dataset = Dataset.by_name("reach_to_grasp", client, api="query", resolved=True)
```
The returned `dataset` is None.

I tried v0.5.1 and 0.4.0 tags, none of them worked - I got HTTPError (I can post the traceback if it will help).

**Comment by GMattheisen** [comment]
The code you provided works for me when supplied with a token from [Nexus](https://nexus-iam.humanbrainproject.org/v0/oauth2/token/HBP?code=f9ft3m&state=9b7ee706-1457-48e9-a263-41b775d7cedc) and not an environmental token. Could you try that approach to see if the code will return the correct result?

![image](https://user-images.githubusercontent.com/35850228/95314083-280aab00-0891-11eb-88c0-145047d0c6c2.png)

**Comment by apdavison** [comment]
I think the link for the tokens should be https://nexus-iam.humanbrainproject.org/v0/oauth2/authorize

**Comment by dizcza** [comment]
I get an error with the Nexus token too.
Does it mean that only specific people could your API to download R2G?
