### ISSUE TITLE
Install fails for non-released dependencies

### ISSUE THREAD

**Issue by terhorstd** [HumanBrainProject/fairgraph#42]
The installation as stated in the README breaks:
```
$ pip install fairgraph
Collecting fairgraph==0.5.1
  Downloading fairgraph-0.5.1.tar.gz (71 kB)
     |████████████████████████████████| 71 kB 2.5 MB/s 
ERROR: Packages installed from PyPI cannot depend on packages which are not also hosted on PyPI.
fairgraph depends on openid_http_client@ git+https://github.com/HumanBrainProject/openid_http_client.git#subdirectory=openid_http_client 
```

**Comment by apdavison** [comment]
thanks Dennis. I'm aware of this problem, which is due to a change in pip.

**Comment by terhorstd** [comment]
Ah, thanks, Andrew!
I filed an issue against openid_http_client anyway to have the software stack properly installable.

**Comment by xgui3783** [comment]
pyxus also seems to be one of these dep?

**Comment by apdavison** [comment]
It is, but pyxus and openid_http_client are needed only for access to KG version 2, so they will be going away as dependencies in a few months once the migration is complete. I've spoken to the KG team about releasing kg-core-python on PyPI, and they said they will prioritise that.

I've removed the non-pip-installable dependencies from setup.py in the latest release, so "pip install fairgraph" works again, and I've updated the installation instructions to make it clear you need to install kg-core-python from Github.

**Comment by apdavison** [comment]
I will also make pyxus and openid_http_client optional dependencies, so that people who only want to access KG v3 don't need to install them.
