### ISSUE TITLE
How to access Dataset description

### ISSUE THREAD

**Issue by mih** [HumanBrainProject/fairgraph#55]
For an example dataset like https://search.kg.ebrains.eu/instances/Dataset/a8932c7e-063c-4131-ab96-996d843998e9 I am trying to get the description, i.e.

![image](https://user-images.githubusercontent.com/136479/205235962-9f39febe-7457-4d60-882d-d2e8c980240b.png)

(screenshot from webpage).

I tried the following code:

```py
In [1]: from fairgraph import KGClient
   ...: client = KGClient()
In [2]: from fairgraph.openminds.core import DatasetVersion
In [3]: dv=DatasetVersion.from_id('a8932c7e-063c-4131-ab96-996d843998e9', client)
/home/mih/env/datalad-dev/lib/python3.10/site-packages/fairgraph/fields.py:256: UserWarning: 'str' object has no attribute 'get'
  warnings.warn(str(err))
/home/mih/env/datalad-dev/lib/python3.10/site-packages/fairgraph/fields.py:96: UserWarning: Field 'full_documentation' is required but was not provided.
  warnings.warn(errmsg)
In [4]: dv.description
Out[4]: ''
In [5]: dv.full_documentation
```

I also traversed all versions of the dataset record via `.is_new_version_of.resolve(client)`, but none of the records contain the text that is shown in the screenshot.

I am looking in the wrong place?

I am using `fairgraph` 0.8.2.

PS: Other properties shown on the webpage are included, such as `version_innovation`. So this does not seems to be a fundamental user error.

**Comment by mih** [comment]
It seems I was indeed looking in the wrong place:

```py
In [11]: from fairgraph.openminds.core import Dataset
In [12]: d = Dataset.from_id('5a16d948-8d1c-400c-b797-8a7ad29944b2', client)
In [13]: d.description
Out[13]: 'This dataset contains the whole-brain parcellation of the Julich-Brain Cytoarchitectonic Atlas in the MNI Colin 27 and / or the MNI ICBM 152 (2009c Nonlinear Asymmetric) coordinate space. The parcellation is derived from the individually released probability maps (PMs) of the cytoarchitectonically defined brain regions. For the whole-brain parcellation, the available PMs are combined into a maximum probability map (MPM) by considering for each voxel the probability of all cytoarchitectonic brain regions, and determining the most probable assignment. In later versions of this dataset, gap maps complement the maximum probability map of the cytoarchitectonically defined brain regions to achieve full cortical coverage. Note that methodological improvements and integration of new brain structures may lead to small deviations in the parcellation between released versions of this dataset.'
```

It is presently unclear to me, how I can discover the dataset (concept) ID `5a16d948-8d1c-400c-b797-8a7ad29944b2` from the dataset version ID `a8932c7e-063c-4131-ab96-996d843998e9`.

**Comment by mih** [comment]
> It is presently unclear to me, how I can discover the dataset (concept) ID `5a16d948-8d1c-400c-b797-8a7ad29944b2` from the dataset version ID `a8932c7e-063c-4131-ab96-996d843998e9`.

The following approach makes this possible

```py
>>> Dataset.from_alias(dv.alias, client).description
'This dataset contains the whole-brain parcellation of the Julich-Brai....
```

but it seems clunky to perform an alias-based look-up, when precise identifiers are available.

Is there a better way?

**Comment by apdavison** [comment]
The [EBRAINS KG graphical UI](https://search.kg.ebrains.eu/) shows the "description" field from the Dataset if the field is empty for the DatasetVersion. (The same is true for "name").

To look up the Dataset without resorting to aliases (which are indeed not guaranteed to work, it's just a curation convention), you can use:

```
d = Dataset.list(client, versions=dv)[0]
```

This seems like a good candidate for adding a convenience method or property, so that, e.g. `dv.get_description()` would perform the lookup on the parent if the field is empty.

**Comment by mih** [comment]
Thanks. I have switched to this approach.
