### ISSUE TITLE
`DatasetVersion` record without `release_date`

### ISSUE THREAD

**Issue by mih** [HumanBrainProject/fairgraph#62]
I am querying `DatasetVersion` `5802e695-98e7-463d-81bc-d7532a80777f`, which has

```py
>>> kg_dsver.is_released(self.client)
True
>>> kg_dsver.version_identifier
'v1.0'
```

but simultaneously

```py
>>> kg_dsver.release_date
None
```

It is hard for me to tell whether this is to be expected (maybe because release date is a property that needs to be set manually (hence could be forgotten) rather than automatically (my assumption).

I will be grateful re feedback on whether my code needs to work around this, what other sources of metadata could function as a timestamp for a dataset version -- ideally something that is guaranteed by the KG to be a universally available property.

**Comment by apdavison** [comment]
This is not a fairgraph question, since it concerns the _contents_ of the EBRAINS KG.

Since this value could in principle be set automatically, I guess it's a question for the KG development team.
