### ISSUE TITLE
Default values are of wrong type when saving to KG

### ISSUE THREAD

**Issue by ehennestad** [HumanBrainProject/fairgraph#65]
When saving some instances to the KG, I get the following error:

TypeError: Expected a string, integer or float for key 'hash', not a <class 'NoneType'>

This happens on fields which are not filled in.

**Comment by ehennestad** [comment]
Some schemas and properties where this fails:

File - hash
Subject - lookup_label
SubjectState - lookup_label

**Comment by apdavison** [comment]
This happens when checking whether the object already exists, and means that one of the fields used to define object identity is empty. A better error message is needed, at least.

**Comment by apdavison** [comment]
This should have been fixed in 489d9e3, with some extra unit tests added in 9c834e0c.
