### ISSUE TITLE
The name of controlledTerms is not following python module name conventions

### ISSUE THREAD

**Issue by Peyman-N** [HumanBrainProject/fairgraph#90]
The name of controlledTerms in fairgraph is `controlledterms` but it should be `controlledTerms`

**Comment by apdavison** [comment]
It should be `controlled_terms`, as in openMINDS-Python.

This change has been made in the current master branch (the old name still works, but emits a deprecation warning), so when we make the next release this ticket can be closed.

**Comment by apdavison** [comment]
(same story with `specimenprep` --> `specimen_prep`)

**Comment by apdavison** [comment]
this change was released in 0.12.1
